- name: Download AWS CLI v2
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"

- name: install zip
  apt:
    name: zip
    state: present

- name: Unzip AWS CLI v2
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: Install AWS CLI v2
  ansible.builtin.command:
    cmd: "/tmp/aws/install --update"
