# meta/main.yml

galaxy_info:
  author: Your Name
  description: Ansible role to install Doppler CLI
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - bionic
        - focal

dependencies: []
