name: Run Ansible with AWS Secret Key

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read inventory file
        id: inventory
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat ansible/hosts.ini >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: ansible/main.yaml
          inventory: ${{ steps.inventory.outputs.content }}
          key: ${{ secrets.DEMO_TEST_PRIVATE_KEY }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
