name: Run Ansible with AWS Secret Key

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ssh-agent with key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}


      - name: Ready-to-use Ansible-Playbook environment
        uses: SakulFlee/GitHub-Action-Ansible@v0.0.1
        with:
          playbook_file: main.yaml
          inventory_file: hosts.ini
          working_directory: ansible

          

