name: Run Ansible with AWS Secret Key

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write private key to file
        run: |
          printf '%s\n' "${{ secrets.DEMO_TEST_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Expose private key content as action output
        id: keyfile
        run: |
          # Write the full PEM into a multiline output variable
          echo "key<<'EOF'" >> $GITHUB_OUTPUT
          cat private_key.pem >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Read inventory file
        id: inventory
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat ansible/hosts.ini >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: ansible/main.yaml
          inventory: ${{ steps.inventory.outputs.content }}
          key: ${{ steps.keyfile.outputs.key }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
