

# Check if Task CLI is already installed
- name: Check if Task is already installed
  stat:
    path: /usr/local/bin/task
  register: task_stat

# Download and install Task CLI if not present
- name: Install Taskfile if not present
  shell: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
  args:
    creates: /usr/local/bin/task
  become: true
  when: not task_stat.stat.exists
  changed_when: true
  tags:
    - taskfile
